name: mapbox_search
description: A Flutter package for place search using MapBox Api and for Static map image
version: 4.1.0-beta.2

homepage: https://github.com/ketanchoyal/mapbox_search

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.1.0
  uuid: ^3.0.7
  color: ^3.0.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.24.2
  meta: ^1.9.1
  http_multi_server: ^3.2.1
